### PR TITLE
minify JSON before parsing to support comments in preprocessed file

### PR DESCRIPTION
**Pull request by hoegertn**

### CODE REVIEW

**Comment by hoegertn** [comment]
Will add some test later today

**Comment by monken** [comment]
Thank you very much. Did not know of jsmin, exactly what I was looking for. I undid the changes to cli.js because that would've broken the cli once installed (run `NODE_PATH=../ node bin/cli.js` from the git repository to test the cli).

**Comment by hoegertn** [comment]
I called npm link to test it and it failed with not finding cfn-include to request. Should be the same with npm i. I looked at many other cli tools and all did it with relative paths. I am not sure why this works for you

**Comment by monken** [comment]
Yep, I can confirm that it also works on Windows with relative paths. That was my only concern. Let's do relative paths then. Thanks for bringing this up!

**Pull request merged**
