### PR TITLE
cli --enable 'env'

### PR DESCRIPTION
**Pull request by nmccready**
Allow included documents to be pre-processed and inject env vars without needing !GetEnv

### CODE REVIEW

**Comment by monken** [comment]
Great idea! I'd prefer this to be more generic. Could we instead have a `--enable env` parameter? That way we could also enable all features individually such as `--enable include,env,map` etc. What do you think?

**Comment by nmccready** [comment]
Yeah sounds good to me . 


I think we really need a follow up PR to covert all the recurse and common functions to just pass one argument of an options object . Cause the amount of arguments is getting rediculous and hard to track.

Also I think the use of bind has to go as it makes finding errors very difficult in my own experience .

**Comment by nmccready** [comment]
Don't merge yet, found a few bugs

**Comment by nmccready** [comment]
Ok should be g2g now

**Comment by nmccready** [comment]
anything else missing?

**Pull request closed without merging**
